### ISSUE TITLE
Add release and package build CI

### ISSUE THREAD

**Issue by JeanPhilippeKernel** [JeanPhilippeKernel/RendererEngine#100]
We want to perform a release operation during the build pipeline, so we can deliver the ZEngine Editor release for each platform in form of zip file

See as an entry point: https://trstringer.com/github-actions-create-release-upload-artifacts/

**Comment by JeanPhilippeKernel** [comment]
@cazteam  would you like to investigate this?  🙂

**Comment by codedei** [comment]
😎
