### ISSUE TITLE
Add precompiled header (pch.h)

### ISSUE THREAD

**Issue by JeanPhilippeKernel** [JeanPhilippeKernel/RendererEngine#113]
We need to pch.h files to accelerate building time 

- [x] ZEngine
- [x] Sandbox2d
- [x] Sandbox3d

**Comment by aristid-lavri** [comment]
Take this

**Comment by JeanPhilippeKernel** [comment]
Marked sandbox3d and sandbox2d as completed as they are being merging into  editor:  #157
