### ISSUE TITLE
Improve MeshBuilder helper

### ISSUE THREAD

**Issue by JeanPhilippeKernel** [JeanPhilippeKernel/RendererEngine#129]
To create a mesh object, we sometimes rely on some existing methods in the builder,
but doing that leads us to double/triple instances creation of the property inside a Mesh object

see : [MeshBuilder header](https://github.com/JeanPhilippeKernel/RendererEngine/blob/develop/ZEngine/include/ZEngine/Rendering/Meshes/MeshBuilder.h)

**Comment by codedei** [comment]
it's available ?

**Comment by JeanPhilippeKernel** [comment]
no longer applicable
