### ISSUE TITLE
Remove & Refacto comments 

### ISSUE THREAD

**Issue by dorgelesn** [JeanPhilippeKernel/RendererEngine#14]
**Remove comments for clean code.**

Target files :
- `Sandbox/src/Assets/Shaders/texture.glsl`
- `Sandbox/src/Layers/ExampleLayer.cpp`
- `Z_Engine/src/LayerStack.cpp`
- `Z_Engine/src/Z_Engine.h`
- `Z_Engine/src/Layers/ImguiLayer.h`
- `Z_Engine/src/Rendering/Buffers/IndexBuffer.h`
- `Z_Engine/src/Rendering/Buffers/VertexArray.h`
- `Z_Engine/src/Rendering/Renderer/GraphicRenderer.h`
- `Z_Engine/src/Rendering/Shaders/Shader.cpp`
- `Z_Engine/src/Window/SDLWin/OpenGLWindow.cpp`
- `Z_Engine/src/Engine.cpp`

**Comment by JeanPhilippeKernel** [comment]
Thanks for opening this issue, really appreciated it 🎉
do not hesitate to open a new one if you find something I can improve or refactor
