### ISSUE TITLE
Add new Texture constructor to support rgba arguments

### ISSUE THREAD

**Issue by JeanPhilippeKernel** [JeanPhilippeKernel/RendererEngine#166]
We want to be able to add r, g, b, a value through the ctor of Texture Class.
we add a new ctor or extend an existing one
See the implementation of Texture2D : https://github.com/JeanPhilippeKernel/RendererEngine/blob/develop/ZEngine/src/Texture2D.cpp

**Comment by JeanPhilippeKernel** [comment]
@JFancis would you like to work on this one ?

**Comment by JFancis** [comment]
Hi,Yes
