### ISSUE TITLE
Implement the Copy  feature of the Log Component

### ISSUE THREAD

**Issue by JeanPhilippeKernel** [JeanPhilippeKernel/RendererEngine#198]
Make the Copy button of Log Component functional

**Comment by JeanPhilippeKernel** [comment]
@JFancis, since you  did work on that component recently, would you like to add this feature

**Comment by JFancis** [comment]
hi yes

**Comment by JeanPhilippeKernel** [comment]
I'm taking back this task because I completed it in PR #210
