### ISSUE TITLE
Improve Shader Compiler

### ISSUE THREAD

**Issue by JeanPhilippeKernel** [JeanPhilippeKernel/RendererEngine#269]
Today, GLSL shader codes are compiled offline during the engine build stage through  glslangValidator tool.

In order to enhance and improve the writing shader experience, we would like to support shader compilation on runtime.
That support will be the foundation of other features like:
+ Writing shader in-engine editor
+ Hot-reloading compiled shader

The offline compilation leverages the support _**GL_GOOGLE_include_directive**_ extension that allows the inclusion of another shader file, the runtime compiler should offer/allow the same feature to preserve the same experience.
 
The existing Shader Compiler was based on OpenGL API, but since we moved to Vulkan we need to rethink the exposed APIs 

- [x] Revisit the existing Shader Compiler to make it compatible with the Vulkan shader compiler API
- [x] Add support for #include<....>
- [x] Add support for runtime compilation

**Comment by jnyfah** [comment]
@JeanPhilippeKernel  please enhance the description

**Comment by JeanPhilippeKernel** [comment]
I updated the description
