### ISSUE TITLE
Revisit existing ShaderManager implementation

### ISSUE THREAD

**Issue by JeanPhilippeKernel** [JeanPhilippeKernel/RendererEngine#303]
We want to simplify the creation of Shader object for Pipeline Specification

As today, the creation the of Shader object for a pipeline is kind hard coded in such way that the user needs to remember the name of the shader file he/her want to load - as we rely on it to retrieve the files.

See: 
[ImGuiRenderer](https://github.com/JeanPhilippeKernel/RendererEngine/blob/develop/ZEngine/src/ImGUIRenderer.cpp#L84)
[RenderPass::UseShader](https://github.com/JeanPhilippeKernel/RendererEngine/blob/develop/ZEngine/src/RenderPass.cpp#L694)

Our goal is to move the impl in Render Pass into a ShaderManager that will be responsible for creating/caching shader objects.
the basic creation of a Shader object should require: (unique key name, the vertex file, the fragment file)

+ Unique Key name: this name will be used as identifier to request the creation or existing shader from the ShaderManager

Back then, when using OpenGL, we had a  [ShaderManager](https://github.com/JeanPhilippeKernel/RendererEngine/blob/develop/ZEngine/src/ShaderManager.cpp) implemented, the new specification above should be able to leverage it and do the necessary changes or improve it .

**Comment by jnyfah** [comment]
@JeanPhilippeKernel !!!

**Comment by JeanPhilippeKernel** [comment]
thanks for the reminder, description updated 🙂
