### ISSUE TITLE
correct the range value of normal color and tint color for texture

### ISSUE THREAD

**Issue by JeanPhilippeKernel** [JeanPhilippeKernel/RendererEngine#31]
partially done,  but we should improve color value, for normal color it's RGB (0 - 255), but for tint color texture it's Vec4 (0f- 1f)

**Comment by BRICEMARCELKOUADIO** [comment]
I'll take this

**Comment by JeanPhilippeKernel** [comment]
sure... I assigned it to you!

**Comment by JeanPhilippeKernel** [comment]
Since we have an editor now, we should verify whether It still is the case and correct it if necessary.
see https://github.com/JeanPhilippeKernel/RendererEngine/blob/develop/Tetragrama/src/Components/InspectorViewUIComponent.cpp -- line 121

**Comment by JeanPhilippeKernel** [comment]
@JFancis would you like to check this out?

**Comment by JFancis** [comment]
Hi yes

**Comment by JeanPhilippeKernel** [comment]
No longer applicable
