### ISSUE TITLE
Panzerfaust - UI - Architecture set-up

### ISSUE THREAD

**Issue by JFancis** [JeanPhilippeKernel/RendererEngine#334]
For the Panzerfaust project, we'll be using the MVVM architecture.
This issue is dedicated to setting it up.
description of MVVM with avaloniaui : https://docs.avaloniaui.net/docs/concepts/the-mvvm-pattern/

**Comment by JeanPhilippeKernel** [comment]
assigned to @BRICEMARCELKOUADIO
