### ISSUE TITLE
Panzerfaust - UI - Add project 

### ISSUE THREAD

**Issue by JFancis** [JeanPhilippeKernel/RendererEngine#338]
Feature : 

This function consists of clicking on a button and then accessing the project creation form, followed by the creation of the project.

Scenario: user clicks on project creation button
    Given user clicks on project creation button
    Then access to the creation form

Scenario: fill in all input fields to create a project
    Given user enters name and description and path 
    When click on the validate button
    Then project creation is carried out

Scenario: fill in the two mandatory fields (name and path) and obtain project creation
    Given user enters name and path
    When click on the validate button
    Then project creation is carried out

Scenario: the user does not fill in one of the mandatory fields and the project is not created
    Given the user does not fill in one of the mandatory fields and the project is not created ( name and path )
    When click on the validate button
    Then the creation of the project is rejected

**Comment by BRICEMARCELKOUADIO** [comment]
assign me this ticket please @JeanPhilippeKernel
