### ISSUE TITLE
Build errors on a fresh git-clone.

### ISSUE THREAD

**Issue by krovee** [JeanPhilippeKernel/RendererEngine#341]
Hola! Im trying to build this project on my machine (Win11, VulkanSDK installed, DirectX tools enabled, etc..) and getting too much errors that are specifically related to circular include issues (thats how it looks for me..).
Maybe Im the one who doing something wrong here?

ps: basically the engine itself compiles fine with zero errors, but when things got to tetragrama - holy cr.. so, take a look at this.

Errors itself:

  DockspaceUIComponent.cpp
C:\Users\krovee\Desktop\RendererEngine\__externals\glm\glm\detail\qualifier.hpp(8,7): error C2011: 'glm::qualifier': 'enum' type redefinition [C:\Users\krovee\Desktop\RendererEngine\Result.Windows.x64.MultiConfig\Tetragrama\src\tetragrama.vcxproj]
C:\Users\krovee\Desktop\RendererEngine\__externals\glm\glm\detail\qualifier.hpp(35,2): error C2572: 'glm::vec': redefinition of default argument: parameter 3 [C:\Users\krovee\Desktop\RendererEngine\Result.Windows.x64.MultiConfig\Tetragrama\src\tetragrama.vcxproj]
C:\Users\krovee\Desktop\RendererEngine\__externals\glm\glm\detail\qualifier.hpp(36,2): error C2572: 'glm::mat': redefinition of default argument: parameter 4 [C:\Users\krovee\Desktop\RendererEngine\Result.Windows.x64.MultiConfig\Tetragrama\src\tetragrama.vcxproj]
C:\Users\krovee\Desktop\RendererEngine\__externals\glm\glm\detail\qualifier.hpp(37,2): error C2572: 'glm::qua': redefinition of default argument: parameter 2 [C:\Users\krovee\Desktop\RendererEngine\Result.Windows.x64.MultiConfig\Tetragrama\src\tetragrama.vcxproj]
C:\Users\krovee\Desktop\RendererEngine\__externals\glm\glm\detail\qualifier.hpp(59,9): error C2953: 'glm::detail::is_aligned': class template has already been defined [C:\Users\krovee\Desktop\RendererEngine\Result.Windows.x64.MultiConfig\Tetragrama\src\tetragrama.vcxproj]
C:\Users\krovee\Desktop\RendererEngine\__externals\glm\glm\detail\qualifier.hpp(85,9): error C2953: 'glm::detail::storage': class template has already been defined [C:\Users\krovee\Desktop\RendererEngine\Result.Windows.x64.MultiConfig\Tetragrama\src\tetragrama.vcxproj]
C:\Users\krovee\Desktop\RendererEngine\__externals\glm\glm\detail\qualifier.hpp(93,3): error C2976: 'glm::detail::storage': too few template arguments [C:\Users\krovee\Desktop\RendererEngine\Result.Windows.x64.MultiConfig\Tetragrama\src\tetragrama.vcxproj]
C:\Users\krovee\Desktop\RendererEngine\__externals\glm\glm\detail\qualifier.hpp(101,21): error C3855: 'glm::detail::storage': template parameter 'T' is incompatible with the declaration [C:\Users\krovee\Desktop\RendererEngine\Result.Windows.x64.MultiConfig\Tetragrama\src\tetragrama.vcxproj]
C:\Users\krovee\Desktop\RendererEngine\__externals\glm\glm\detail\qualifier.hpp(101,3): error C2976: 'glm::detail::storage': too few template arguments [C:\Users\krovee\Desktop\RendererEngine\Result.Windows.x64.MultiConfig\Tetragrama\src\tetragrama.vcxproj]
C:\Users\krovee\Desktop\RendererEngine\__externals\glm\glm\detail\qualifier.hpp(190,7): error C2011: 'glm::detail::genTypeEnum': 'enum' type redefinition [C:\Users\krovee\Desktop\RendererEngine\Result.Windows.x64.MultiConfig\Tetragrama\src\tetragrama.vcxproj]
C:\Users\krovee\Desktop\RendererEngine\__externals\glm\glm\detail\qualifier.hpp(198,9): error C2953: 'glm::detail::genTypeTrait': class template has already been defined [C:\Users\krovee\Desktop\RendererEngine\Result.Windows.x64.MultiConfig\Tetragrama\src\tetragrama.vcxproj]
C:\Users\krovee\Desktop\RendererEngine\__externals\glm\glm\detail\qualifier.hpp(201,21): error C3855: 'glm::detail::genTypeTrait': template parameter 'C' is incompatible with the declaration [C:\Users\krovee\Desktop\RendererEngine\Result.Windows.x64.MultiConfig\Tetragrama\src\tetragrama.vcxproj]
C:\Users\krovee\Desktop\RendererEngine\__externals\glm\glm\detail\qualifier.hpp(201,2): error C2977: 'glm::detail::genTypeTrait': too many template arguments [C:\Users\krovee\Desktop\RendererEngine\Result.Windows.x64.MultiConfig\Tetragrama\src\tetragrama.vcxproj]
C:\Users\krovee\Desktop\RendererEngine\__externals\glm\glm\detail\qualifier.hpp(208,9): error C2953: 'glm::detail::init_gentype': class template has already been defined [C:\Users\krovee\Desktop\RendererEngine\Result.Windows.x64.MultiConfig\Tetragrama\src\tetragrama.vcxproj]
C:\Users\krovee\Desktop\RendererEngine\__externals\glm\glm\detail\qualifier.hpp(212,2): error C2976: 'glm::detail::init_gentype': too few template arguments [C:\Users\krovee\Desktop\RendererEngine\Result.Windows.x64.MultiConfig\Tetragrama\src\tetragrama.vcxproj]
C:\Users\krovee\Desktop\RendererEngine\__externals\glm\glm\detail\qualifier.hpp(221,2): error C2976: 'glm::detail::init_gentype': too few template arguments [C:\Users\krovee\Desktop\RendererEngine\Result.Windows.x64.MultiConfig\Tetragrama\src\tetragrama.vcxproj]
C:\Users\krovee\Desktop\RendererEngine\__externals\glm\glm\detail\type_vec2.hpp(17,9): error C2953: 'glm::vec<2,T,Q>': class template has already been defined [C:\Users\krovee\Desktop\RendererEngine\Result.Windows.x64.MultiConfig\Tetragrama\src\tetragrama.vcxproj]
C:\Users\krovee\Desktop\RendererEngine\__externals\glm\glm\detail\compute_vector_relational.hpp(11,9): error C2953: 'glm::detail::compute_equal': class template has already been defined [C:\Users\krovee\Desktop\RendererEngine\Result.Windows.x64.MultiConfig\Tetragrama\src\tetragrama.vcxproj]
C:\Users\krovee\Desktop\RendererEngine\__externals\glm\glm\detail\type_vec2.inl(27,49): error C2995: 'glm::vec<2,T,Q>::vec(const glm::vec<2,T,P> &)': function template has already been defined [C:\Users\krovee\Desktop\RendererEngine\Result.Windows.x64.MultiConfig\Tetragrama\src\tetragrama.vcxproj]
C:\Users\krovee\Desktop\RendererEngine\__externals\glm\glm\detail\type_vec2.inl(34,49): error C2995: 'glm::vec<2,T,Q>::vec(T)': function template has already been defined [C:\Users\krovee\Desktop\RendererEngine\Result.Windows.x64.MultiConfig\Tetragrama\src\tetragrama.vcxproj]
C:\Users\krovee\Desktop\RendererEngine\__externals\glm\glm\detail\type_vec2.inl(39,49): error C2995: 'glm::vec<2,T,Q>::vec(T,T)': function template has already been defined [C:\Users\krovee\Desktop\RendererEngine\Result.Windows.x64.MultiConfig\Tetragrama\src\tetragrama.vcxproj]
C:\Users\krovee\Desktop\RendererEngine\__externals\glm\glm\detail\type_vec2.inl(47,49): error C2995: 'glm::vec<2,T,Q>::vec(const glm::vec<1,U,P> &)': function template has already been defined [C:\Users\krovee\Desktop\RendererEngine\Result.Windows.x64.MultiConfig\Tetragrama\src\tetragrama.vcxproj]
C:\Users\krovee\Desktop\RendererEngine\__externals\glm\glm\detail\type_vec2.inl(54,49): error C2995: 'glm::vec<2,T,Q>::vec(A,B)': function template has already been defined [C:\Users\krovee\Desktop\RendererEngine\Result.Windows.x64.MultiConfig\Tetragrama\src\tetragrama.vcxproj]
C:\Users\krovee\Desktop\RendererEngine\__externals\glm\glm\detail\type_vec2.inl(61,49): error C2995: 'glm::vec<2,T,Q>::vec(const glm::vec<1,A,Q> &,B)': function template has already been defined [C:\Users\krovee\Desktop\RendererEngine\Result.Windows.x64.MultiConfig\Tetragrama\src\tetragrama.vcxproj]
C:\Users\krovee\Desktop\RendererEngine\__externals\glm\glm\detail\type_vec2.inl(68,49): error C2995: 'glm::vec<2,T,Q>::vec(A,const glm::vec<1,B,Q> &)': function template has already been defined [C:\Users\krovee\Desktop\RendererEngine\Result.Windows.x64.MultiConfig\Tetragrama\src\tetragrama.vcxproj]
C:\Users\krovee\Desktop\RendererEngine\__externals\glm\glm\detail\type_vec2.inl(75,49): error C2995: 'glm::vec<2,T,Q>::vec(const glm::vec<1,A,Q> &,const glm::vec<1,B,Q> &)': function template has already been defined [C:\Users\krovee\Desktop\RendererEngine\Result.Windows.x64.MultiConfig\Tetragrama\src\tetragrama.vcxproj]
C:\Users\krovee\Desktop\RendererEngine\__externals\glm\glm\detail\type_vec2.inl(84,49): error C2995: 'glm::vec<2,T,Q>::vec(const glm::vec<2,U,P> &)': function template has already been defined [C:\Users\krovee\Desktop\RendererEngine\Result.Windows.x64.MultiConfig\Tetragrama\src\tetragrama.vcxproj]
C:\Users\krovee\Desktop\RendererEngine\__externals\glm\glm\detail\type_vec2.inl(91,49): error C2995: 'glm::vec<2,T,Q>::vec(const glm::vec<3,U,P> &)': function template has already been defined [C:\Users\krovee\Desktop\RendererEngine\Result.Windows.x64.MultiConfig\Tetragrama\src\tetragrama.vcxproj]
C:\Users\krovee\Desktop\RendererEngine\__externals\glm\glm\detail\type_vec2.inl(98,49): error C2995: 'glm::vec<2,T,Q>::vec(const glm::vec<4,U,P> &)': function template has already been defined [C:\Users\krovee\Desktop\RendererEngine\Result.Windows.x64.MultiConfig\Tetragrama\src\tetragrama.vcxproj]
C:\Users\krovee\Desktop\RendererEngine\__externals\glm\glm\detail\type_vec2.inl(106,53): error C2995: 'T &glm::vec<2,T,Q>::operator [](glm::vec<2,T,Q>::length_type)': function template has already been defined [C:\Users\krovee\Desktop\RendererEngine\Result.Windows.x64.MultiConfig\Tetragrama\src\tetragrama.vcxproj]
C:\Users\krovee\Desktop\RendererEngine\__externals\glm\glm\detail\type_vec2.inl(120,58): error C2995: 'const T &glm::vec<2,T,Q>::operator [](glm::vec<2,T,Q>::length_type) const': function template has already been defined [C:\Users\krovee\Desktop\RendererEngine\Result.Windows.x64.MultiConfig\Tetragrama\src\tetragrama.vcxproj]
C:\Users\krovee\Desktop\RendererEngine\__externals\glm\glm\detail\type_vec2.inl(147,64): error C2995: 'glm::vec<2,T,Q> &glm::vec<2,T,Q>::operator =(const glm::vec<2,U,Q> &)': function template has already been defined [C:\Users\krovee\Desktop\RendererEngine\Result.Windows.x64.MultiConfig\Tetragrama\src\tetragrama.vcxproj]
C:\Users\krovee\Desktop\RendererEngine\__externals\glm\glm\detail\type_vec2.inl(156,64): error C2995: 'glm::vec<2,T,Q> &glm::vec<2,T,Q>::operator +=(U)': function template has already been defined [C:\Users\krovee\Desktop\RendererEngine\Result.Windows.x64.MultiConfig\Tetragrama\src\tetragrama.vcxproj]
C:\Users\krovee\Desktop\RendererEngine\__externals\glm\glm\detail\type_vec2.inl(165,64): error C2995: 'glm::vec<2,T,Q> &glm::vec<2,T,Q>::operator +=(const glm::vec<1,A,Q> &)': function template has already been defined [C:\Users\krovee\Desktop\RendererEngine\Result.Windows.x64.MultiConfig\Tetragrama\src\tetragrama.vcxproj]
C:\Users\krovee\Desktop\RendererEngine\__externals\glm\glm\detail\type_vec2.inl(174,64): error C2995: 'glm::vec<2,T,Q> &glm::vec<2,T,Q>::operator +=(const glm::vec<2,U,Q> &)': function template has already been defined [C:\Users\krovee\Desktop\RendererEngine\Result.Windows.x64.MultiConfig\Tetragrama\src\tetragrama.vcxproj]
C:\Users\krovee\Desktop\RendererEngine\__externals\glm\glm\detail\type_vec2.inl(183,64): error C2995: 'glm::vec<2,T,Q> &glm::vec<2,T,Q>::operator -=(U)': function template has already been defined [C:\Users\krovee\Desktop\RendererEngine\Result.Windows.x64.MultiConfig\Tetragrama\src\tetragrama.vcxproj]
C:\Users\krovee\Desktop\RendererEngine\__externals\glm\glm\detail\type_vec2.inl(192,64): error C2995: 'glm::vec<2,T,Q> &glm::vec<2,T,Q>::operator -=(const glm::vec<1,A,Q> &)': function template has already been defined [C:\Users\krovee\Desktop\RendererEngine\Result.Windows.x64.MultiConfig\Tetragrama\src\tetragrama.vcxproj]
C:\Users\krovee\Desktop\RendererEngine\__externals\glm\glm\detail\type_vec2.inl(201,64): error C2995: 'glm::vec<2,T,Q> &glm::vec<2,T,Q>::operator -=(const glm::vec<2,U,Q> &)': function template has already been defined [C:\Users\krovee\Desktop\RendererEngine\Result.Windows.x64.MultiConfig\Tetragrama\src\tetragrama.vcxproj]
C:\Users\krovee\Desktop\RendererEngine\__externals\glm\glm\detail\type_vec2.inl(210,64): error C2995: 'glm::vec<2,T,Q> &glm::vec<2,T,Q>::operator *=(U)': function template has already been defined [C:\Users\krovee\Desktop\RendererEngine\Result.Windows.x64.MultiConfig\Tetragrama\src\tetragrama.vcxproj]
C:\Users\krovee\Desktop\RendererEngine\__externals\glm\glm\detail\type_vec2.inl(219,64): error C2995: 'glm::vec<2,T,Q> &glm::vec<2,T,Q>::operator *=(const glm::vec<1,A,Q> &)': function template has already been defined [C:\Users\krovee\Desktop\RendererEngine\Result.Windows.x64.MultiConfig\Tetragrama\src\tetragrama.vcxproj]
C:\Users\krovee\Desktop\RendererEngine\__externals\glm\glm\detail\type_vec2.inl(228,64): error C2995: 'glm::vec<2,T,Q> &glm::vec<2,T,Q>::operator *=(const glm::vec<2,U,Q> &)': function template has already been defined [C:\Users\krovee\Desktop\RendererEngine\Result.Windows.x64.MultiConfig\Tetragrama\src\tetragrama.vcxproj]
C:\Users\krovee\Desktop\RendererEngine\__externals\glm\glm\detail\type_vec2.inl(237,64): error C2995: 'glm::vec<2,T,Q> &glm::vec<2,T,Q>::operator /=(U)': function template has already been defined [C:\Users\krovee\Desktop\RendererEngine\Result.Windows.x64.MultiConfig\Tetragrama\src\tetragrama.vcxproj]
C:\Users\krovee\Desktop\RendererEngine\__externals\glm\glm\detail\type_vec2.inl(246,64): error C2995: 'glm::vec<2,T,Q> &glm::vec<2,T,Q>::operator /=(const glm::vec<1,A,Q> &)': function template has already been defined [C:\Users\krovee\Desktop\RendererEngine\Result.Windows.x64.MultiConfig\Tetragrama\src\tetragrama.vcxproj]
C:\Users\krovee\Desktop\RendererEngine\__externals\glm\glm\detail\type_vec2.inl(255,64): error C2995: 'glm::vec<2,T,Q> &glm::vec<2,T,Q>::operator /=(const glm::vec<2,U,Q> &)': function template has already been defined [C:\Users\krovee\Desktop\RendererEngine\Result.Windows.x64.MultiConfig\Tetragrama\src\tetragrama.vcxproj]
C:\Users\krovee\Desktop\RendererEngine\__externals\glm\glm\detail\type_vec2.inl(265,64): error C2995: 'glm::vec<2,T,Q> &glm::vec<2,T,Q>::operator ++(void)': function template has already been defined [C:\Users\krovee\Desktop\RendererEngine\Result.Windows.x64.MultiConfig\Tetragrama\src\tetragrama.vcxproj]
C:\Users\krovee\Desktop\RendererEngine\__externals\glm\glm\detail\type_vec2.inl(273,64): error C2995: 'glm::vec<2,T,Q> &glm::vec<2,T,Q>::operator --(void)': function template has already been defined [C:\Users\krovee\Desktop\RendererEngine\Result.Windows.x64.MultiConfig\Tetragrama\src\tetragrama.vcxproj]
C:\Users\krovee\Desktop\RendererEngine\__externals\glm\glm\detail\type_vec2.inl(281,62): error C2995: 'glm::vec<2,T,Q> glm::vec<2,T,Q>::operator ++(int)': function template has already been defined [C:\Users\krovee\Desktop\RendererEngine\Result.Windows.x64.MultiConfig\Tetragrama\src\tetragrama.vcxproj]
C:\Users\krovee\Desktop\RendererEngine\__externals\glm\glm\detail\type_vec2.inl(289,62): error C2995: 'glm::vec<2,T,Q> glm::vec<2,T,Q>::operator --(int)': function template has already been defined [C:\Users\krovee\Desktop\RendererEngine\Result.Windows.x64.MultiConfig\Tetragrama\src\tetragrama.vcxproj]
C:\Users\krovee\Desktop\RendererEngine\__externals\glm\glm\detail\type_vec2.inl(300,64): error C2995: 'glm::vec<2,T,Q> &glm::vec<2,T,Q>::operator %=(U)': function template has already been defined [C:\Users\krovee\Desktop\RendererEngine\Result.Windows.x64.MultiConfig\Tetragrama\src\tetragrama.vcxproj]
C:\Users\krovee\Desktop\RendererEngine\__externals\glm\glm\detail\type_vec2.inl(309,64): error C2995: 'glm::vec<2,T,Q> &glm::vec<2,T,Q>::operator %=(const glm::vec<1,A,Q> &)': function template has already been defined [C:\Users\krovee\Desktop\RendererEngine\Result.Windows.x64.MultiConfig\Tetragrama\src\tetragrama.vcxproj]
C:\Users\krovee\Desktop\RendererEngine\__externals\glm\glm\detail\type_vec2.inl(318,64): error C2995: 'glm::vec<2,T,Q> &glm::vec<2,T,Q>::operator %=(const glm::vec<2,U,Q> &)': function template has already been defined [C:\Users\krovee\Desktop\RendererEngine\Result.Windows.x64.MultiConfig\Tetragrama\src\tetragrama.vcxproj]
C:\Users\krovee\Desktop\RendererEngine\__externals\glm\glm\detail\type_vec2.inl(327,64): error C2995: 'glm::vec<2,T,Q> &glm::vec<2,T,Q>::operator &=(U)': function template has already been defined [C:\Users\krovee\Desktop\RendererEngine\Result.Windows.x64.MultiConfig\Tetragrama\src\tetragrama.vcxproj]
C:\Users\krovee\Desktop\RendererEngine\__externals\glm\glm\detail\type_vec2.inl(336,64): error C2995: 'glm::vec<2,T,Q> &glm::vec<2,T,Q>::operator &=(const glm::vec<1,A,Q> &)': function template has already been defined [C:\Users\krovee\Desktop\RendererEngine\Result.Windows.x64.MultiConfig\Tetragrama\src\tetragrama.vcxproj]
C:\Users\krovee\Desktop\RendererEngine\__externals\glm\glm\detail\type_vec2.inl(345,64): error C2995: 'glm::vec<2,T,Q> &glm::vec<2,T,Q>::operator &=(const glm::vec<2,U,Q> &)': function template has already been defined [C:\Users\krovee\Desktop\RendererEngine\Result.Windows.x64.MultiConfig\Tetragrama\src\tetragrama.vcxproj]
C:\Users\krovee\Desktop\RendererEngine\__externals\glm\glm\detail\type_vec2.inl(354,64): error C2995: 'glm::vec<2,T,Q> &glm::vec<2,T,Q>::operator |=(U)': function template has already been defined [C:\Users\krovee\Desktop\RendererEngine\Result.Windows.x64.MultiConfig\Tetragrama\src\tetragrama.vcxproj]
C:\Users\krovee\Desktop\RendererEngine\__externals\glm\glm\detail\type_vec2.inl(363,64): error C2995: 'glm::vec<2,T,Q> &glm::vec<2,T,Q>::operator |=(const glm::vec<1,A,Q> &)': function template has already been defined [C:\Users\krovee\Desktop\RendererEngine\Result.Windows.x64.MultiConfig\Tetragrama\src\tetragrama.vcxproj]
C:\Users\krovee\Desktop\RendererEngine\__externals\glm\glm\detail\type_vec2.inl(372,64): error C2995: 'glm::vec<2,T,Q> &glm::vec<2,T,Q>::operator |=(const glm::vec<2,U,Q> &)': function template has already been defined [C:\Users\krovee\Desktop\RendererEngine\Result.Windows.x64.MultiConfig\Tetragrama\src\tetragrama.vcxproj]
C:\Users\krovee\Desktop\RendererEngine\__externals\glm\glm\detail\type_vec2.inl(381,64): error C2995: 'glm::vec<2,T,Q> &glm::vec<2,T,Q>::operator ^=(U)': function template has already been defined [C:\Users\krovee\Desktop\RendererEngine\Result.Windows.x64.MultiConfig\Tetragrama\src\tetragrama.vcxproj]
C:\Users\krovee\Desktop\RendererEngine\__externals\glm\glm\detail\type_vec2.inl(390,64): error C2995: 'glm::vec<2,T,Q> &glm::vec<2,T,Q>::operator ^=(const glm::vec<1,A,Q> &)': function template has already been defined [C:\Users\krovee\Desktop\RendererEngine\Result.Windows.x64.MultiConfig\Tetragrama\src\tetragrama.vcxproj]
C:\Users\krovee\Desktop\RendererEngine\__externals\glm\glm\detail\type_vec2.inl(399,64): error C2995: 'glm::vec<2,T,Q> &glm::vec<2,T,Q>::operator ^=(const glm::vec<2,U,Q> &)': function template has already been defined [C:\Users\krovee\Desktop\RendererEngine\Result.Windows.x64.MultiConfig\Tetragrama\src\tetragrama.vcxproj]
C:\Users\krovee\Desktop\RendererEngine\__externals\glm\glm\detail\type_vec2.inl(408,64): error C2995: 'glm::vec<2,T,Q> &glm::vec<2,T,Q>::operator <<=(U)': function template has already been defined [C:\Users\krovee\Desktop\RendererEngine\Result.Windows.x64.MultiConfig\Tetragrama\src\tetragrama.vcxproj]
C:\Users\krovee\Desktop\RendererEngine\__externals\glm\glm\detail\type_vec2.inl(417,64): error C2995: 'glm::vec<2,T,Q> &glm::vec<2,T,Q>::operator <<=(const glm::vec<1,A,Q> &)': function template has already been defined [C:\Users\krovee\Desktop\RendererEngine\Result.Windows.x64.MultiConfig\Tetragrama\src\tetragrama.vcxproj]
C:\Users\krovee\Desktop\RendererEngine\__externals\glm\glm\detail\type_vec2.inl(426,64): error C2995: 'glm::vec<2,T,Q> &glm::vec<2,T,Q>::operator <<=(const glm::vec<2,U,Q> &)': function template has already been defined [C:\Users\krovee\Desktop\RendererEngine\Result.Windows.x64.MultiConfig\Tetragrama\src\tetragrama.vcxproj]
C:\Users\krovee\Desktop\RendererEngine\__externals\glm\glm\detail\type_vec2.inl(435,64): error C2995: 'glm::vec<2,T,Q> &glm::vec<2,T,Q>::operator >>=(U)': function template has already been defined [C:\Users\krovee\Desktop\RendererEngine\Result.Windows.x64.MultiConfig\Tetragrama\src\tetragrama.vcxproj]
C:\Users\krovee\Desktop\RendererEngine\__externals\glm\glm\detail\type_vec2.inl(444,64): error C2995: 'glm::vec<2,T,Q> &glm::vec<2,T,Q>::operator >>=(const glm::vec<1,A,Q> &)': function template has already been defined [C:\Users\krovee\Desktop\RendererEngine\Result.Windows.x64.MultiConfig\Tetragrama\src\tetragrama.vcxproj]
C:\Users\krovee\Desktop\RendererEngine\__externals\glm\glm\detail\type_vec2.inl(453,64): error C2995: 'glm::vec<2,T,Q> &glm::vec<2,T,Q>::operator >>=(const glm::vec<2,U,Q> &)': function template has already been defined [C:\Users\krovee\Desktop\RendererEngine\Result.Windows.x64.MultiConfig\Tetragrama\src\tetragrama.vcxproj]

How it looks in the terminal:
![image](https://github.com/JeanPhilippeKernel/RendererEngine/assets/152976005/38b3808f-d980-4a72-9aad-b77f887625cf)

**Comment by JeanPhilippeKernel** [comment]
Hello @krovee 
Thanks for the feedback, 
During the installation of vulkan sdk, can please confirm if you unchecked the GLM headers component?

If not, please uncheck the GLM headers component and retry

The conflict arises because the GLM library was added prior to transitioning to the Vulkan SDK, and its GLM component is causing clashes during the installation.

**Comment by JeanPhilippeKernel** [comment]
Thanks @krovee for reporting this issue.  I now fixed and then closed it 🙂
Feel free to re-open it if you find another problem during a fresh git-clone.
