### ISSUE TITLE
Separate Panzefaust and ZEngine build

### ISSUE THREAD

**Issue by JeanPhilippeKernel** [JeanPhilippeKernel/RendererEngine#358]
As today, to build Panzerfaust, developers have to run the build engine script which will go through the whole build process, that depending on the platform can be extremely long.

The idea here is to introduce, ideally a switch option to the current build script that will skip the engine build and and only build panzerfaust.

This can look like: BuildEngine.ps1 -OnlyLauncher

**Comment by aristid-lavri** [comment]
Comment
