### ISSUE TITLE
Add Contributing.md documentation

### ISSUE THREAD

**Issue by JeanPhilippeKernel** [JeanPhilippeKernel/RendererEngine#81]
It'll be nice, for new contributors to have a step they can follow to set up the repository locally
and how they can format their pull request to facilitate the triages process (like description, changes, fix) etc...

**Comment by JFancis** [comment]
Hi, Can i work on it

**Comment by JeanPhilippeKernel** [comment]
Sure 🙂, I've assigned it to you

**Comment by JFancis** [comment]
thanks you
